<?php

namespace Database\Seeders;

use App\Models\Partner;
use Illuminate\Database\Seeder;

/**
 * Restaurants Dakar fournis par le métier (liste saisie manuellement).
 * NB: horaires en texte libre pour affichage + calcul ouvert/fermé.
 */
class DakarRestaurantsSeeder extends Seeder
{
    public function run(): void
    {
        $entries = [
            [
                'name' => 'Restaurant Le Lagon 1',
                'category' => 'restaurant',
                'description' => 'Cuisine: Fruits de mer',
                'address' => 'Plateau, Dakar',
                'latitude' => 14.6676,
                'longitude' => -17.4285,
                'phone' => '+221 33 821 53 22',
                'email' => null,
                'website' => null,
                'rating' => 4.4,
                'opening_hours' => '9h-0h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'La Fourchette',
                'category' => 'restaurant',
                'description' => 'Cuisine: Gastronomique',
                'address' => 'Plateau, Dakar',
                'latitude' => 14.6703,
                'longitude' => -17.428,
                'phone' => '+221 33 842 66 66',
                'email' => null,
                'website' => null,
                'rating' => 4.3,
                'opening_hours' => '12h-23h Lun-Sam',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'La Parrilla',
                'category' => 'restaurant',
                'description' => 'Cuisine: Viandes/Grill',
                'address' => 'Plateau, Dakar',
                'latitude' => 14.6639,
                'longitude' => -17.4344,
                'phone' => '+221 33 822 15 00',
                'email' => null,
                'website' => null,
                'rating' => 4.4,
                'opening_hours' => '12h-23h Mar-Dim',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'La Pampa',
                'category' => 'restaurant',
                'description' => 'Cuisine: Argentine',
                'address' => 'Plateau, Dakar',
                'latitude' => 14.6697,
                'longitude' => -17.4302,
                'phone' => '+221 33 889 50 70',
                'email' => null,
                'website' => null,
                'rating' => 4.1,
                'opening_hours' => '7h-23h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Restaurant Chez Loutcha',
                'category' => 'restaurant',
                'description' => 'Cuisine: Sénégalaise',
                'address' => 'Plateau, Dakar',
                'latitude' => 14.6686,
                'longitude' => -17.435,
                'phone' => '+221 33 821 03 02',
                'email' => null,
                'website' => null,
                'rating' => 3.9,
                'opening_hours' => '12h-22h Lun-Sam',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Bidew',
                'category' => 'restaurant',
                'description' => 'Cuisine: Africaine',
                'address' => 'Plateau, Dakar',
                'latitude' => 14.6682,
                'longitude' => -17.4358,
                'phone' => '+221 33 823 19 09',
                'email' => null,
                'website' => null,
                'rating' => 4.2,
                'opening_hours' => '9h-0h Lun-Sam',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Restaurant Le Dagorne',
                'category' => 'restaurant',
                'description' => 'Cuisine: Français/Poisson',
                'address' => 'Plateau, Dakar',
                'latitude' => 14.6711,
                'longitude' => -17.4286,
                'phone' => '+221 33 825 71 97',
                'email' => null,
                'website' => null,
                'rating' => 4.2,
                'opening_hours' => '12h-23h Lun-Sam',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Nostra Restaurant',
                'category' => 'restaurant',
                'description' => 'Cuisine: Italien',
                'address' => 'Plateau, Dakar',
                'latitude' => 14.6666,
                'longitude' => -17.4325,
                'phone' => '+221 77 698 06 06',
                'email' => null,
                'website' => null,
                'rating' => 4.3,
                'opening_hours' => '12h-23h Lun-Sam',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Le Coste Dakar',
                'category' => 'restaurant',
                'description' => 'Cuisine: Internationale',
                'address' => 'Plateau, Dakar',
                'latitude' => 14.6694,
                'longitude' => -17.4315,
                'phone' => '+221 33 822 54 55',
                'email' => null,
                'website' => null,
                'rating' => 4.2,
                'opening_hours' => '11h-0h Lun-Sam',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Caesar\'s République',
                'category' => 'restaurant',
                'description' => 'Cuisine: Brasserie',
                'address' => 'Plateau, Dakar',
                'latitude' => 14.6651,
                'longitude' => -17.436,
                'phone' => '+221 33 823 84 00',
                'email' => null,
                'website' => null,
                'rating' => 4.0,
                'opening_hours' => '8h-1h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Restaurant La Terrasse (Terrou-Bi)',
                'category' => 'restaurant',
                'description' => 'Cuisine: Gastronomique',
                'address' => 'Corniche Ouest, Dakar',
                'latitude' => 14.6763,
                'longitude' => -17.4662,
                'phone' => '+221 33 839 90 40',
                'email' => null,
                'website' => null,
                'rating' => 4.3,
                'opening_hours' => '12h-23h30 ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Urbanista',
                'category' => 'restaurant',
                'description' => 'Cuisine: Bistro',
                'address' => 'Point E, Dakar',
                'latitude' => 14.7006,
                'longitude' => -17.4623,
                'phone' => '+221 33 869 06 00',
                'email' => null,
                'website' => null,
                'rating' => 4.6,
                'opening_hours' => '8h-0h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'La Favela',
                'category' => 'restaurant',
                'description' => 'Cuisine: Internationale',
                'address' => 'Point E, Dakar',
                'latitude' => 14.6992,
                'longitude' => -17.4644,
                'phone' => '+221 71 036 30 30',
                'email' => null,
                'website' => null,
                'rating' => 4.2,
                'opening_hours' => '11h-2h Mar-Dim',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Trattoria da Alex',
                'category' => 'restaurant',
                'description' => 'Cuisine: Italienne',
                'address' => 'Fann, Dakar',
                'latitude' => 14.6949,
                'longitude' => -17.4579,
                'phone' => null,
                'email' => null,
                'website' => null,
                'rating' => 4.3,
                'opening_hours' => '9h-0h Lun-Sam',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Restaurant BUUMY',
                'category' => 'restaurant',
                'description' => 'Cuisine: Africaine',
                'address' => 'Fann, Dakar',
                'latitude' => 14.6933,
                'longitude' => -17.4577,
                'phone' => '+221 33 864 22 64',
                'email' => null,
                'website' => null,
                'rating' => 4.0,
                'opening_hours' => '7h-0h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Le Jardin Thaïlandais',
                'category' => 'restaurant',
                'description' => 'Cuisine: Thaï',
                'address' => 'Fann, Dakar',
                'latitude' => 14.6931,
                'longitude' => -17.4602,
                'phone' => '+221 33 825 58 33',
                'email' => null,
                'website' => null,
                'rating' => 4.1,
                'opening_hours' => '12h-23h Lun-Sam',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Noliane Terrazza',
                'category' => 'restaurant',
                'description' => 'Cuisine: Terrasse/Internationale',
                'address' => 'Point E, Dakar',
                'latitude' => 14.6984,
                'longitude' => -17.4693,
                'phone' => '+221 71 017 98 98',
                'email' => null,
                'website' => null,
                'rating' => 4.4,
                'opening_hours' => '7h-23h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'O Wok Bar Point E',
                'category' => 'restaurant',
                'description' => 'Cuisine: Asiatique',
                'address' => 'Point E, Dakar',
                'latitude' => 14.6945,
                'longitude' => -17.4562,
                'phone' => '+221 78 170 61 61',
                'email' => null,
                'website' => null,
                'rating' => 4.6,
                'opening_hours' => '12h-23h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Restaurant Swiss Palace',
                'category' => 'restaurant',
                'description' => 'Cuisine: Internationale/Chicha',
                'address' => 'Point E, Dakar',
                'latitude' => 14.6977,
                'longitude' => -17.46,
                'phone' => '+221 77 442 22 22',
                'email' => null,
                'website' => null,
                'rating' => 3.7,
                'opening_hours' => '7h30-4h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Le Mermoz',
                'category' => 'restaurant',
                'description' => 'Cuisine: Brasserie/Bar',
                'address' => 'Mermoz, Dakar',
                'latitude' => 14.7026,
                'longitude' => -17.4723,
                'phone' => '+221 33 822 61 66',
                'email' => null,
                'website' => null,
                'rating' => 3.7,
                'opening_hours' => '8h-4h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Le Ndajé',
                'category' => 'restaurant',
                'description' => 'Cuisine: Sénégalaise',
                'address' => 'Sacré Cœur, Dakar',
                'latitude' => 14.716,
                'longitude' => -17.4692,
                'phone' => '+221 77 307 25 66',
                'email' => null,
                'website' => null,
                'rating' => 3.8,
                'opening_hours' => '7h-20h Lun + 24h Mar-Sam',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Piazzola',
                'category' => 'restaurant',
                'description' => 'Cuisine: Pizza/Italienne',
                'address' => 'Mermoz, Dakar',
                'latitude' => 14.7084,
                'longitude' => -17.4797,
                'phone' => '+221 33 860 36 14',
                'email' => null,
                'website' => null,
                'rating' => 4.0,
                'opening_hours' => '11h-0h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Elite Coffee Dakar',
                'category' => 'restaurant',
                'description' => 'Cuisine: Café/Internationale',
                'address' => 'Sacré Cœur, Dakar',
                'latitude' => 14.714,
                'longitude' => -17.4662,
                'phone' => '+221 77 506 39 39',
                'email' => null,
                'website' => null,
                'rating' => 3.8,
                'opening_hours' => '7h-0h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'THE GRILL',
                'category' => 'restaurant',
                'description' => 'Cuisine: Américaine/Burger',
                'address' => 'Mermoz, Dakar',
                'latitude' => 14.7091,
                'longitude' => -17.4718,
                'phone' => '+221 76 589 66 66',
                'email' => null,
                'website' => null,
                'rating' => 4.2,
                'opening_hours' => null,
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Alma\'s Bistro',
                'category' => 'restaurant',
                'description' => 'Cuisine: Bistro',
                'address' => 'Mermoz, Dakar',
                'latitude' => 14.7077,
                'longitude' => -17.4859,
                'phone' => '+221 77 855 14 74',
                'email' => null,
                'website' => null,
                'rating' => 4.2,
                'opening_hours' => '8h30-23h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Pizza Time Sacré Cœur',
                'category' => 'restaurant',
                'description' => 'Cuisine: Pizza',
                'address' => 'Sacré Cœur, Dakar',
                'latitude' => 14.716,
                'longitude' => -17.4707,
                'phone' => '+221 30 120 20 20',
                'email' => null,
                'website' => null,
                'rating' => 3.9,
                'opening_hours' => '11h-2h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Grill Time Dakar',
                'category' => 'restaurant',
                'description' => 'Cuisine: Grillades',
                'address' => 'Sacré Cœur, Dakar',
                'latitude' => 14.716,
                'longitude' => -17.4707,
                'phone' => '+221 30 120 00 67',
                'email' => null,
                'website' => null,
                'rating' => 4.5,
                'opening_hours' => '12h-2h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'La Maison BINAF',
                'category' => 'restaurant',
                'description' => 'Cuisine: Gastronomique',
                'address' => 'Sacré Cœur, Dakar',
                'latitude' => 14.7173,
                'longitude' => -17.4609,
                'phone' => '+221 77 280 89 89',
                'email' => null,
                'website' => null,
                'rating' => 4.8,
                'opening_hours' => '10h-23h30 ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Blu Sky',
                'category' => 'restaurant',
                'description' => 'Cuisine: Bar/Grill/Chicha',
                'address' => 'Sacré Cœur, Dakar',
                'latitude' => 14.7193,
                'longitude' => -17.4648,
                'phone' => '+221 77 606 41 41',
                'email' => null,
                'website' => null,
                'rating' => 3.7,
                'opening_hours' => '17h-3h Lun-Ven',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Chez OBAM',
                'category' => 'restaurant',
                'description' => 'Cuisine: Camerounaise',
                'address' => 'Sacré Cœur, Dakar',
                'latitude' => 14.7194,
                'longitude' => -17.472,
                'phone' => '+221 77 671 36 48',
                'email' => null,
                'website' => null,
                'rating' => 4.2,
                'opening_hours' => '11h-0h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Wonderfood Sacré Cœur',
                'category' => 'restaurant',
                'description' => 'Cuisine: Fast food/Wraps',
                'address' => 'Sacré Cœur, Dakar',
                'latitude' => 14.7167,
                'longitude' => -17.4691,
                'phone' => '+221 77 150 48 48',
                'email' => null,
                'website' => null,
                'rating' => 3.8,
                'opening_hours' => '10h-5h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Chicken Street Dakar',
                'category' => 'restaurant',
                'description' => 'Cuisine: Poulet/Naan',
                'address' => 'Sacré Cœur, Dakar',
                'latitude' => 14.7161,
                'longitude' => -17.4701,
                'phone' => '+221 78 686 59 72',
                'email' => null,
                'website' => null,
                'rating' => 4.4,
                'opening_hours' => '11h30-2h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'RESTAURANT DAKAR (SC)',
                'category' => 'restaurant',
                'description' => 'Cuisine: Internationale',
                'address' => 'Sacré Cœur, Dakar',
                'latitude' => 14.7166,
                'longitude' => -17.4676,
                'phone' => '+221 77 671 11 49',
                'email' => null,
                'website' => null,
                'rating' => 5.0,
                'opening_hours' => '8h-3h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Restaurant La Pointe des Almadies',
                'category' => 'restaurant',
                'description' => 'Cuisine: Poisson/Fruits de mer',
                'address' => 'Almadies, Dakar',
                'latitude' => 14.7454,
                'longitude' => -17.528,
                'phone' => '+221 33 820 01 40',
                'email' => null,
                'website' => null,
                'rating' => 4.0,
                'opening_hours' => '12h-0h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Le Cabanon Dakar',
                'category' => 'restaurant',
                'description' => 'Cuisine: Vue mer',
                'address' => 'Almadies, Dakar',
                'latitude' => 14.739,
                'longitude' => -17.5169,
                'phone' => '+221 33 820 43 00',
                'email' => null,
                'website' => null,
                'rating' => 4.2,
                'opening_hours' => '12h-23h30 Mar-Dim',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Chez Fatou',
                'category' => 'restaurant',
                'description' => 'Cuisine: Sénégalaise/Poisson',
                'address' => 'Almadies, Dakar',
                'latitude' => 14.7409,
                'longitude' => -17.5213,
                'phone' => '+221 33 820 92 38',
                'email' => null,
                'website' => null,
                'rating' => 4.0,
                'opening_hours' => '8h30-0h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Restaurant Le Carré',
                'category' => 'restaurant',
                'description' => 'Cuisine: Grill/Cocktails',
                'address' => 'Almadies, Dakar',
                'latitude' => 14.7409,
                'longitude' => -17.5225,
                'phone' => '+221 33 823 33 26',
                'email' => null,
                'website' => null,
                'rating' => 4.0,
                'opening_hours' => '11h-3h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Exotik Beach',
                'category' => 'restaurant',
                'description' => 'Cuisine: Plage/Grillades',
                'address' => 'Almadies, Dakar',
                'latitude' => 14.7397,
                'longitude' => -17.5179,
                'phone' => '+221 77 152 58 58',
                'email' => null,
                'website' => null,
                'rating' => 4.4,
                'opening_hours' => '11h-2h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Skynest Bar & Lounge',
                'category' => 'restaurant',
                'description' => 'Cuisine: Bar/Lounge',
                'address' => 'Almadies, Dakar',
                'latitude' => 14.741,
                'longitude' => -17.5206,
                'phone' => '+221 78 609 35 35',
                'email' => null,
                'website' => null,
                'rating' => 4.9,
                'opening_hours' => '12h-2h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'COP21 Restaurant',
                'category' => 'restaurant',
                'description' => 'Cuisine: Poisson/Vue mer',
                'address' => 'Almadies, Dakar',
                'latitude' => 14.7392,
                'longitude' => -17.517,
                'phone' => '+221 77 364 90 33',
                'email' => null,
                'website' => null,
                'rating' => 4.2,
                'opening_hours' => '9h-2h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'KOTAO Coffee',
                'category' => 'restaurant',
                'description' => 'Cuisine: Café/Brunch',
                'address' => 'Almadies, Dakar',
                'latitude' => 14.7433,
                'longitude' => -17.521,
                'phone' => '+221 77 718 76 52',
                'email' => null,
                'website' => null,
                'rating' => 4.4,
                'opening_hours' => '8h-23h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Casa Teranga',
                'category' => 'restaurant',
                'description' => 'Cuisine: Vegan/Pizza/Sain',
                'address' => 'Almadies, Dakar',
                'latitude' => 14.745,
                'longitude' => -17.5285,
                'phone' => '+221 78 451 15 10',
                'email' => null,
                'website' => null,
                'rating' => 4.7,
                'opening_hours' => '12h-23h Mar-Dim',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Seven Seven Dakar',
                'category' => 'restaurant',
                'description' => 'Cuisine: Steak/Gastronomique',
                'address' => 'Almadies, Dakar',
                'latitude' => 14.7511,
                'longitude' => -17.5025,
                'phone' => '+221 78 593 78 78',
                'email' => null,
                'website' => null,
                'rating' => 4.7,
                'opening_hours' => '12h-2h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Noflaye Beach',
                'category' => 'restaurant',
                'description' => 'Cuisine: Plage/Fruits de mer',
                'address' => 'Ngor, Dakar',
                'latitude' => 14.7409,
                'longitude' => -17.5218,
                'phone' => '+221 33 820 30 32',
                'email' => null,
                'website' => null,
                'rating' => 4.1,
                'opening_hours' => '10h-22h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Caffe Noliane',
                'category' => 'restaurant',
                'description' => 'Cuisine: Bistro/Italien',
                'address' => 'Ngor, Dakar',
                'latitude' => 14.7425,
                'longitude' => -17.5197,
                'phone' => '+221 77 379 71 50',
                'email' => null,
                'website' => null,
                'rating' => 4.4,
                'opening_hours' => '7h-23h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Restaurant Le Ngor Pieds dans l\'eau',
                'category' => 'restaurant',
                'description' => 'Cuisine: Vue mer',
                'address' => 'Ngor, Dakar',
                'latitude' => 14.741,
                'longitude' => -17.5248,
                'phone' => '+221 77 504 30 06',
                'email' => null,
                'website' => null,
                'rating' => 3.9,
                'opening_hours' => '10h-1h30 Mer-Dim',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'La Cabane du Pêcheur',
                'category' => 'restaurant',
                'description' => 'Cuisine: Fruits de mer',
                'address' => 'Ngor, Dakar',
                'latitude' => 14.7497,
                'longitude' => -17.5112,
                'phone' => '+221 33 820 76 75',
                'email' => null,
                'website' => null,
                'rating' => 4.2,
                'opening_hours' => '8h-23h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'La Plage Dakar',
                'category' => 'restaurant',
                'description' => 'Cuisine: Internationale',
                'address' => 'Ngor, Dakar',
                'latitude' => 14.7407,
                'longitude' => -17.5204,
                'phone' => '+221 78 860 53 65',
                'email' => null,
                'website' => null,
                'rating' => 4.1,
                'opening_hours' => '10h-23h Mar-Dim',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'YOUYOU (Hôtel BOMA)',
                'category' => 'restaurant',
                'description' => 'Cuisine: Gastronomique',
                'address' => 'Almadies, Dakar',
                'latitude' => 14.7501,
                'longitude' => -17.5037,
                'phone' => '+221 77 737 38 41',
                'email' => null,
                'website' => null,
                'rating' => 4.8,
                'opening_hours' => null,
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Melo\'s Patisserie aux Mamelles',
                'category' => 'restaurant',
                'description' => 'Cuisine: Brunch/Pâtisserie',
                'address' => 'Mamelles, Dakar',
                'latitude' => 14.7228,
                'longitude' => -17.4986,
                'phone' => '+221 78 389 19 94',
                'email' => null,
                'website' => null,
                'rating' => 4.3,
                'opening_hours' => '8h-20h30 ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Panam\'as Ouakam',
                'category' => 'restaurant',
                'description' => 'Cuisine: Burger',
                'address' => 'Ouakam, Dakar',
                'latitude' => 14.7279,
                'longitude' => -17.4921,
                'phone' => '+221 33 824 71 99',
                'email' => null,
                'website' => null,
                'rating' => 4.0,
                'opening_hours' => '11h-0h Lun-Ven',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Teranga Grill Coffee',
                'category' => 'restaurant',
                'description' => 'Cuisine: Grill/Piscine',
                'address' => 'Ouakam, Dakar',
                'latitude' => 14.7325,
                'longitude' => -17.4977,
                'phone' => '+221 78 167 39 39',
                'email' => null,
                'website' => null,
                'rating' => 4.1,
                'opening_hours' => '10h30-0h Mar-Dim',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Phare des Mamelles',
                'category' => 'restaurant',
                'description' => 'Cuisine: Gastronomique/Show',
                'address' => 'Mamelles, Dakar',
                'latitude' => 14.7236,
                'longitude' => -17.5015,
                'phone' => '+221 77 343 72 72',
                'email' => null,
                'website' => null,
                'rating' => 4.3,
                'opening_hours' => '17h-2h Mar-Dim',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'The Lounge Dakar',
                'category' => 'restaurant',
                'description' => 'Cuisine: BBQ/Brunch',
                'address' => 'Ouakam, Dakar',
                'latitude' => 14.7327,
                'longitude' => -17.4977,
                'phone' => '+221 78 465 69 41',
                'email' => null,
                'website' => null,
                'rating' => 4.5,
                'opening_hours' => '12h-2h30 ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Matcha Café Dakar',
                'category' => 'restaurant',
                'description' => 'Cuisine: Japonaise/Sushi',
                'address' => 'Mamelles, Dakar',
                'latitude' => 14.7237,
                'longitude' => -17.4991,
                'phone' => '+221 33 824 48 05',
                'email' => null,
                'website' => null,
                'rating' => 4.4,
                'opening_hours' => '10h-22h Mar-Dim',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Teral',
                'category' => 'restaurant',
                'description' => 'Cuisine: Africaine authentique',
                'address' => 'Ouakam, Dakar',
                'latitude' => 14.7182,
                'longitude' => -17.4875,
                'phone' => '+221 33 860 75 97',
                'email' => null,
                'website' => null,
                'rating' => 4.1,
                'opening_hours' => '11h-22h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'La Maison de la Crêpe Dakar',
                'category' => 'restaurant',
                'description' => 'Cuisine: Crêperie',
                'address' => 'Ouakam, Dakar',
                'latitude' => 14.7274,
                'longitude' => -17.4931,
                'phone' => '+221 78 736 79 12',
                'email' => null,
                'website' => null,
                'rating' => 4.9,
                'opening_hours' => '11h-23h30 ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Yum-Yum Ouakam',
                'category' => 'restaurant',
                'description' => 'Cuisine: Pizza/Fast food',
                'address' => 'Ouakam, Dakar',
                'latitude' => 14.7183,
                'longitude' => -17.4867,
                'phone' => '+221 33 865 62 62',
                'email' => null,
                'website' => null,
                'rating' => 3.7,
                'opening_hours' => '8h-23h30 ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Hotel du Phare Les Mamelles',
                'category' => 'restaurant',
                'description' => 'Cuisine: Pizza/Brasserie',
                'address' => 'Mamelles, Dakar',
                'latitude' => 14.7301,
                'longitude' => -17.5014,
                'phone' => '+221 33 860 30 00',
                'email' => null,
                'website' => null,
                'rating' => 3.9,
                'opening_hours' => 'Ouvert 24h/24',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Al Mahdi Restaurant Yoff',
                'category' => 'restaurant',
                'description' => 'Cuisine: Marocaine/Internationale',
                'address' => 'Yoff, Dakar',
                'latitude' => 14.755,
                'longitude' => -17.4674,
                'phone' => '+221 33 848 25 35',
                'email' => null,
                'website' => null,
                'rating' => 3.6,
                'opening_hours' => 'Ouvert 24h/24',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'ANIMA PIZZERIA Plage BCEAO',
                'category' => 'restaurant',
                'description' => 'Cuisine: Pizza au feu de bois',
                'address' => 'Yoff, Dakar',
                'latitude' => 14.7619,
                'longitude' => -17.4624,
                'phone' => '+221 78 173 57 22',
                'email' => null,
                'website' => null,
                'rating' => 4.8,
                'opening_hours' => '13h30-0h30 ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Sea & Salt',
                'category' => 'restaurant',
                'description' => 'Cuisine: Indienne/Multinationale',
                'address' => 'Yoff, Dakar',
                'latitude' => 14.7536,
                'longitude' => -17.4952,
                'phone' => '+221 78 178 69 69',
                'email' => null,
                'website' => null,
                'rating' => 4.7,
                'opening_hours' => '11h50-23h50 ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Lala Beach',
                'category' => 'restaurant',
                'description' => 'Cuisine: Plage/Grill',
                'address' => 'Yoff, Dakar',
                'latitude' => 14.7621,
                'longitude' => -17.4615,
                'phone' => '+221 78 117 35 61',
                'email' => null,
                'website' => null,
                'rating' => 4.1,
                'opening_hours' => '9h30-0h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Pizzammore',
                'category' => 'restaurant',
                'description' => 'Cuisine: Pizza Italienne',
                'address' => 'Yoff, Dakar',
                'latitude' => 14.7574,
                'longitude' => -17.4866,
                'phone' => '+221 77 122 09 49',
                'email' => null,
                'website' => null,
                'rating' => 4.3,
                'opening_hours' => '19h-0h Lun+Mer-Dim',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'La Dolce Vita',
                'category' => 'restaurant',
                'description' => 'Cuisine: Italienne',
                'address' => 'Yoff, Dakar',
                'latitude' => 14.7518,
                'longitude' => -17.4928,
                'phone' => '+221 77 715 34 03',
                'email' => null,
                'website' => null,
                'rating' => 4.5,
                'opening_hours' => '9h-0h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'LE TANDEM Restaurant Lounge',
                'category' => 'restaurant',
                'description' => 'Cuisine: Internationale/Lounge',
                'address' => 'Yoff, Dakar',
                'latitude' => 14.7512,
                'longitude' => -17.4607,
                'phone' => '+221 77 695 53 53',
                'email' => null,
                'website' => null,
                'rating' => 4.3,
                'opening_hours' => '12h-3h Lun + Mar-Dim',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Cayor Grill',
                'category' => 'restaurant',
                'description' => 'Cuisine: Grill/Sénégalaise',
                'address' => 'Yoff, Dakar',
                'latitude' => 14.7557,
                'longitude' => -17.4679,
                'phone' => '+221 33 868 15 49',
                'email' => null,
                'website' => null,
                'rating' => 4.4,
                'opening_hours' => '12h-23h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'La Brioche Dorée Grand Yoff',
                'category' => 'restaurant',
                'description' => 'Cuisine: Fast food/Boulangerie',
                'address' => 'Grand Yoff, Dakar',
                'latitude' => 14.7361,
                'longitude' => -17.4553,
                'phone' => '+221 33 867 05 11',
                'email' => null,
                'website' => null,
                'rating' => 3.5,
                'opening_hours' => 'Ouvert 24h/24',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Sunu Dibiterie',
                'category' => 'restaurant',
                'description' => 'Cuisine: Dibiterie/BBQ',
                'address' => 'Grand Yoff, Dakar',
                'latitude' => 14.74,
                'longitude' => -17.4578,
                'phone' => '+221 78 595 17 17',
                'email' => null,
                'website' => null,
                'rating' => 4.9,
                'opening_hours' => '12h-3h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Restaurant Taif In House',
                'category' => 'restaurant',
                'description' => 'Cuisine: Internationale',
                'address' => 'Grand Yoff, Dakar',
                'latitude' => 14.7438,
                'longitude' => -17.4516,
                'phone' => '+221 78 389 90 90',
                'email' => null,
                'website' => null,
                'rating' => 4.6,
                'opening_hours' => '8h30-0h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Monalisa Crêperie',
                'category' => 'restaurant',
                'description' => 'Cuisine: Crêperie',
                'address' => 'Grand Yoff, Dakar',
                'latitude' => 14.7333,
                'longitude' => -17.4513,
                'phone' => '+221 78 788 65 71',
                'email' => null,
                'website' => null,
                'rating' => 5.0,
                'opening_hours' => '9h30-23h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Le Comptoir',
                'category' => 'restaurant',
                'description' => 'Cuisine: Pizza/Burger/Wraps',
                'address' => 'Grand Yoff, Dakar',
                'latitude' => 14.7228,
                'longitude' => -17.4647,
                'phone' => '+221 77 104 05 00',
                'email' => null,
                'website' => null,
                'rating' => 4.0,
                'opening_hours' => '11h-1h30 ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'LE PELICAN RESTAURANT',
                'category' => 'restaurant',
                'description' => 'Cuisine: Gastronomique',
                'address' => 'Grand Yoff, Dakar',
                'latitude' => 14.7395,
                'longitude' => -17.4679,
                'phone' => '+221 77 142 28 28',
                'email' => null,
                'website' => null,
                'rating' => 4.3,
                'opening_hours' => '8h-3h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Resto Ivoirien Grand Yoff',
                'category' => 'restaurant',
                'description' => 'Cuisine: Ivoirienne',
                'address' => 'Grand Yoff, Dakar',
                'latitude' => 14.7392,
                'longitude' => -17.4503,
                'phone' => '+221 77 205 40 36',
                'email' => null,
                'website' => null,
                'rating' => 4.3,
                'opening_hours' => 'Dim seulement 8h-21h30',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Damas Boulangerie',
                'category' => 'restaurant',
                'description' => 'Cuisine: Boulangerie/Pizza',
                'address' => 'Grand Yoff, Dakar',
                'latitude' => 14.7355,
                'longitude' => -17.4725,
                'phone' => '+221 77 292 09 09',
                'email' => null,
                'website' => null,
                'rating' => 4.0,
                'opening_hours' => '6h30-22h30 Lun-Ven',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Restaurant Dakar',
                'category' => 'restaurant',
                'description' => 'Cuisine: Internationale',
                'address' => 'Sacré Cœur, Dakar',
                'latitude' => 14.7119,
                'longitude' => -17.4813,
                'phone' => '+221 77 461 70 31',
                'email' => null,
                'website' => null,
                'rating' => 5.0,
                'opening_hours' => '11h-0h ts les jours',
                'logo_url' => null,
                'is_sponsor' => false,
                'visit_count' => 0,
                'is_active' => true,
            ],
        ];

        foreach ($entries as $row) {
            Partner::query()->updateOrCreate(
                ['name' => $row['name'], 'category' => 'restaurant'],
                $row
            );
        }
    }
}
