<?php

namespace Database\Seeders;

use App\Models\Partner;
use Illuminate\Database\Seeder;

class DiplomaticMissionSeeder extends Seeder
{
    /**
     * Seed embassies and consulates in Dakar.
     *
     * Coordinates are provided for direct map usage in the mobile app.
     */
    public function run(): void
    {
        $missions = [
            [
                'name' => 'Ambassade France',
                'category' => 'embassy',
                'description' => 'Représentation diplomatique française à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6683,
                'longitude' => -17.4276,
                'phone' => '+221338395100',
                'email' => null,
                'website' => 'https://sn.ambafrance.org',
                'rating' => 3.6,
                'opening_hours' => '8h-17h Lun-Ven',
            ],
            [
                'name' => 'Consulat France',
                'category' => 'consulate',
                'description' => 'Consulat de France à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6685,
                'longitude' => -17.4300,
                'phone' => '+221338395262',
                'email' => null,
                'website' => 'https://sn.diplomatie.gouv.fr/consulat-general-de-france-dakar',
                'rating' => 2.6,
                'opening_hours' => '8h15-16h30 Lun-Jeu',
            ],
            [
                'name' => 'Ambassade Royaume-Uni',
                'category' => 'embassy',
                'description' => 'British Embassy in Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6597,
                'longitude' => -17.4355,
                'phone' => '+221338237392',
                'email' => null,
                'website' => 'https://www.gov.uk/world/senegal',
                'rating' => 4.5,
                'opening_hours' => '8h-16h30 Lun-Ven',
            ],
            [
                'name' => 'Ambassade Allemagne',
                'category' => 'embassy',
                'description' => 'Ambassade d Allemagne à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6610,
                'longitude' => -17.4368,
                'phone' => '+221338894884',
                'email' => null,
                'website' => 'https://dakar.diplo.de',
                'rating' => 3.7,
                'opening_hours' => '9h-12h Lun-Ven',
            ],
            [
                'name' => 'Ambassade Belgique',
                'category' => 'embassy',
                'description' => 'Ambassade de Belgique à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6590,
                'longitude' => -17.4351,
                'phone' => '+221338894390',
                'email' => null,
                'website' => null,
                'rating' => 4.4,
                'opening_hours' => '8h-16h30 Lun-Ven',
            ],
            [
                'name' => 'Ambassade Espagne',
                'category' => 'embassy',
                'description' => 'Ambassade d Espagne à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6628,
                'longitude' => -17.4359,
                'phone' => '+221338211178',
                'email' => null,
                'website' => null,
                'rating' => 3.7,
                'opening_hours' => '9h-17h Lun-Sam',
            ],
            [
                'name' => 'Ambassade Italie',
                'category' => 'embassy',
                'description' => 'Ambassade d Italie à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6649,
                'longitude' => -17.4411,
                'phone' => '+221338892636',
                'email' => null,
                'website' => 'https://ambdakar.esteri.it',
                'rating' => 3.6,
                'opening_hours' => '9h30-16h Lun-Ven',
            ],
            [
                'name' => 'Ambassade Portugal',
                'category' => 'embassy',
                'description' => 'Ambassade du Portugal à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6953,
                'longitude' => -17.4715,
                'phone' => '+221774801510',
                'email' => null,
                'website' => null,
                'rating' => 3.6,
                'opening_hours' => '9h-17h Lun-Ven',
            ],
            [
                'name' => 'Ambassade Pays-Bas',
                'category' => 'embassy',
                'description' => 'Ambassade des Pays-Bas.',
                'address' => 'Dakar',
                'latitude' => 14.6635,
                'longitude' => -17.4375,
                'phone' => '+221338292121',
                'email' => null,
                'website' => 'https://www.netherlandsandyou.nl/web/senegal',
                'rating' => 3.7,
                'opening_hours' => '8h30-16h30 Lun-Ven',
            ],
            [
                'name' => 'Ambassade Autriche',
                'category' => 'embassy',
                'description' => 'Ambassade d Autriche à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6638,
                'longitude' => -17.4361,
                'phone' => '+221338494000',
                'email' => null,
                'website' => null,
                'rating' => 3.6,
                'opening_hours' => 'Lun/Mer/Jeu 9h-12h',
            ],
            [
                'name' => 'Consulat de Suède',
                'category' => 'consulate',
                'description' => 'Consulat de Suède à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6999,
                'longitude' => -17.4613,
                'phone' => '+221338243336',
                'email' => null,
                'website' => null,
                'rating' => 4.6,
                'opening_hours' => '9h-13h Lun-Ven',
            ],
            [
                'name' => 'Consulat Russie',
                'category' => 'consulate',
                'description' => 'Consulat de Russie à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6668,
                'longitude' => -17.4410,
                'phone' => '+221338215960',
                'email' => null,
                'website' => null,
                'rating' => 3.9,
                'opening_hours' => 'Lun/Mer/Ven 9h-12h',
            ],
            [
                'name' => 'Ambassade Ukraine',
                'category' => 'embassy',
                'description' => 'Ambassade d Ukraine à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.7383,
                'longitude' => -17.5069,
                'phone' => '+221338590202',
                'email' => null,
                'website' => null,
                'rating' => 4.4,
                'opening_hours' => '9h-18h Lun-Sam',
            ],
            [
                'name' => 'Ambassade USA',
                'category' => 'embassy',
                'description' => 'Embassy of the United States in Dakar.',
                'address' => 'Route des Almadies, Dakar',
                'latitude' => 14.7451,
                'longitude' => -17.5261,
                'phone' => '+221338794000',
                'email' => null,
                'website' => 'https://sn.usembassy.gov',
                'rating' => 4.0,
                'opening_hours' => '8h-17h30 Lun-Ven',
            ],
            [
                'name' => 'Ambassade Canada',
                'category' => 'embassy',
                'description' => 'Ambassade du Canada à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6615,
                'longitude' => -17.4381,
                'phone' => '+221338894700',
                'email' => null,
                'website' => 'https://www.international.gc.ca/country-pays/senegal',
                'rating' => 3.8,
                'opening_hours' => '8h-17h Lun-Ven',
            ],
            [
                'name' => 'Ambassade Brésil',
                'category' => 'embassy',
                'description' => 'Ambassade du Brésil à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6941,
                'longitude' => -17.4594,
                'phone' => '+221338259400',
                'email' => null,
                'website' => null,
                'rating' => 3.9,
                'opening_hours' => 'Lun-Ven',
            ],
            [
                'name' => 'Ambassade Cuba',
                'category' => 'embassy',
                'description' => 'Ambassade de Cuba à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.7008,
                'longitude' => -17.4763,
                'phone' => null,
                'email' => null,
                'website' => null,
                'rating' => 2.7,
                'opening_hours' => null,
            ],
            [
                'name' => 'Ambassade Chine',
                'category' => 'embassy',
                'description' => 'Ambassade de Chine à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6937,
                'longitude' => -17.4716,
                'phone' => '+221338697701',
                'email' => null,
                'website' => 'http://sn.china-embassy.gov.cn',
                'rating' => 3.8,
                'opening_hours' => null,
            ],
            [
                'name' => 'Ambassade Japon',
                'category' => 'embassy',
                'description' => 'Ambassade du Japon à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6713,
                'longitude' => -17.4459,
                'phone' => '+221338495500',
                'email' => null,
                'website' => null,
                'rating' => 3.8,
                'opening_hours' => null,
            ],
            [
                'name' => 'Ambassade Corée du Sud',
                'category' => 'embassy',
                'description' => 'Ambassade de Corée du Sud à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.7385,
                'longitude' => -17.5157,
                'phone' => '+221338240672',
                'email' => null,
                'website' => null,
                'rating' => 4.1,
                'opening_hours' => '8h30-17h Lun-Ven',
            ],
            [
                'name' => 'Ambassade Arabie Saoudite',
                'category' => 'embassy',
                'description' => 'Ambassade d Arabie Saoudite à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.7008,
                'longitude' => -17.4740,
                'phone' => '+221338640141',
                'email' => null,
                'website' => null,
                'rating' => 4.0,
                'opening_hours' => null,
            ],
            [
                'name' => 'Consulat Émirats Arabes',
                'category' => 'consulate',
                'description' => 'Consulat des Émirats Arabes Unis.',
                'address' => 'Dakar',
                'latitude' => 14.7029,
                'longitude' => -17.4733,
                'phone' => '+221338699898',
                'email' => null,
                'website' => null,
                'rating' => 3.0,
                'opening_hours' => '9h-15h30 Lun-Ven',
            ],
            [
                'name' => 'Ambassade Iran',
                'category' => 'embassy',
                'description' => 'Ambassade d Iran à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6967,
                'longitude' => -17.4689,
                'phone' => '+221338252528',
                'email' => null,
                'website' => null,
                'rating' => 3.8,
                'opening_hours' => null,
            ],
            [
                'name' => 'Ambassade Pakistan',
                'category' => 'embassy',
                'description' => 'Ambassade du Pakistan à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.7006,
                'longitude' => -17.4725,
                'phone' => '+221338246135',
                'email' => null,
                'website' => null,
                'rating' => 4.8,
                'opening_hours' => '9h-17h Lun-Ven',
            ],
            [
                'name' => 'Ambassade Inde',
                'category' => 'embassy',
                'description' => 'Ambassade de l Inde à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6656,
                'longitude' => -17.4388,
                'phone' => '+221338495875',
                'email' => null,
                'website' => null,
                'rating' => 4.3,
                'opening_hours' => null,
            ],
            [
                'name' => 'Ambassade Turquie',
                'category' => 'embassy',
                'description' => 'Ambassade de Turquie à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.7171,
                'longitude' => -17.4931,
                'phone' => '+221338698076',
                'email' => 'ambassade.dakar@mfa.gov.tr',
                'website' => 'https://dakar-be.mfa.gov.tr',
                'rating' => 3.9,
                'opening_hours' => '9h-18h Lun-Ven',
            ],
            [
                'name' => 'Ambassade Maroc',
                'category' => 'embassy',
                'description' => 'Ambassade du Maroc à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6996,
                'longitude' => -17.4693,
                'phone' => '+221338243836',
                'email' => null,
                'website' => null,
                'rating' => 3.4,
                'opening_hours' => '8h-15h ts les jours',
            ],
            [
                'name' => 'Ambassade Algérie',
                'category' => 'embassy',
                'description' => 'Ambassade d Algérie à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6608,
                'longitude' => -17.4373,
                'phone' => null,
                'email' => null,
                'website' => null,
                'rating' => 4.2,
                'opening_hours' => null,
            ],
            [
                'name' => 'Ambassade Égypte',
                'category' => 'embassy',
                'description' => 'Ambassade d Égypte à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.7008,
                'longitude' => -17.4764,
                'phone' => '+221338695544',
                'email' => null,
                'website' => null,
                'rating' => 4.0,
                'opening_hours' => null,
            ],
            [
                'name' => 'Ambassade Afrique du Sud',
                'category' => 'embassy',
                'description' => 'Ambassade d Afrique du Sud à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.7014,
                'longitude' => -17.4675,
                'phone' => '+221338651959',
                'email' => null,
                'website' => null,
                'rating' => 3.7,
                'opening_hours' => '7h30-16h30 Lun-Ven',
            ],
            [
                'name' => 'Ambassade Nigeria',
                'category' => 'embassy',
                'description' => 'Ambassade du Nigeria à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6892,
                'longitude' => -17.4720,
                'phone' => '+221704699497',
                'email' => null,
                'website' => null,
                'rating' => 3.8,
                'opening_hours' => null,
            ],
            [
                'name' => 'Ambassade Ghana',
                'category' => 'embassy',
                'description' => 'Ambassade du Ghana à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.7072,
                'longitude' => -17.4712,
                'phone' => '+221338691990',
                'email' => null,
                'website' => null,
                'rating' => 4.1,
                'opening_hours' => '9h-14h Lun-Ven',
            ],
            [
                'name' => 'Ambassade Cameroun',
                'category' => 'embassy',
                'description' => 'Ambassade du Cameroun à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6631,
                'longitude' => -17.4354,
                'phone' => '+221338233396',
                'email' => null,
                'website' => null,
                'rating' => 4.0,
                'opening_hours' => '8h30-16h30 Lun-Ven',
            ],
            [
                'name' => 'Ambassade Gabon',
                'category' => 'embassy',
                'description' => 'Ambassade du Gabon à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.7431,
                'longitude' => -17.5160,
                'phone' => '+221338652234',
                'email' => null,
                'website' => null,
                'rating' => 4.1,
                'opening_hours' => '9h-16h Lun-Ven',
            ],
            [
                'name' => 'Ambassade Burkina Faso',
                'category' => 'embassy',
                'description' => 'Ambassade du Burkina Faso à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.7183,
                'longitude' => -17.4871,
                'phone' => '+221338604280',
                'email' => null,
                'website' => null,
                'rating' => 4.5,
                'opening_hours' => null,
            ],
            [
                'name' => 'Consulat Togo',
                'category' => 'consulate',
                'description' => 'Consulat du Togo à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.7234,
                'longitude' => -17.4534,
                'phone' => '+221338258206',
                'email' => null,
                'website' => null,
                'rating' => 3.8,
                'opening_hours' => '9h-16h Lun-Ven',
            ],
            [
                'name' => 'Ambassade Mali',
                'category' => 'embassy',
                'description' => 'Ambassade du Mali à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6878,
                'longitude' => -17.4702,
                'phone' => '+221338246250',
                'email' => null,
                'website' => null,
                'rating' => 4.1,
                'opening_hours' => '9h-16h Lun-Ven',
            ],
            [
                'name' => 'Ambassade Mauritanie',
                'category' => 'embassy',
                'description' => 'Ambassade de Mauritanie à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6910,
                'longitude' => -17.4466,
                'phone' => '+221338235311',
                'email' => null,
                'website' => null,
                'rating' => 4.1,
                'opening_hours' => '9h-12h Ven',
            ],
            [
                'name' => 'Ambassade Guinée Conakry',
                'category' => 'embassy',
                'description' => 'Ambassade de Guinée Conakry.',
                'address' => 'Dakar',
                'latitude' => 14.7332,
                'longitude' => -17.5013,
                'phone' => null,
                'email' => null,
                'website' => null,
                'rating' => 3.6,
                'opening_hours' => null,
            ],
            [
                'name' => 'Ambassade Guinée Bissau',
                'category' => 'embassy',
                'description' => 'Ambassade de Guinée Bissau.',
                'address' => 'Dakar',
                'latitude' => 14.7092,
                'longitude' => -17.4829,
                'phone' => null,
                'email' => null,
                'website' => null,
                'rating' => 2.8,
                'opening_hours' => null,
            ],
            [
                'name' => 'Ambassade Gambie',
                'category' => 'embassy',
                'description' => 'Ambassade de Gambie à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.7513,
                'longitude' => -17.4919,
                'phone' => '+221338201198',
                'email' => null,
                'website' => null,
                'rating' => 3.9,
                'opening_hours' => '8h30-16h Lun-Ven',
            ],
            [
                'name' => 'Ambassade Sierra Leone',
                'category' => 'embassy',
                'description' => 'Ambassade de Sierra Leone à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.6711,
                'longitude' => -17.4275,
                'phone' => '+221338423120',
                'email' => null,
                'website' => null,
                'rating' => 3.8,
                'opening_hours' => null,
            ],
            [
                'name' => 'Ambassade Bénin',
                'category' => 'embassy',
                'description' => 'Ambassade du Bénin à Dakar.',
                'address' => 'Dakar',
                'latitude' => 14.7176,
                'longitude' => -17.4585,
                'phone' => null,
                'email' => null,
                'website' => null,
                'rating' => 4.2,
                'opening_hours' => '9h-16h Lun-Ven',
            ],
        ];

        foreach ($missions as $mission) {
            Partner::updateOrCreate(
                ['name' => $mission['name']],
                array_merge($mission, [
                    'logo_url' => null,
                    'is_sponsor' => false,
                    'visit_count' => 0,
                    'is_active' => true,
                ])
            );
        }
    }
}
